pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {                 
                // Clone the repository from GitHub
                url: 'git@github.com:sandeshmarakini/coit-simple-microservice.git'
            }
        }
        
        stage('Build') {
            steps {      
                // Build the Java project
                sh 'cd coit-backend1 && mvn clean package'
            }
        }
        
        stage('Test') {
            steps {
                // Run tests for the Java project
                sh 'cd coit-backend1 && mvn test'
            }
        }
        
	stage('Deploy') {
            steps {
                // Deploy the Java project
                sh 'cd coit-backend1 && mvn deploy'
            }
        }

        stage('Docker Build') {
            steps {
                // Build Docker image
                sh 'cd coit-backend1 && docker build -t sandeshmarakini/pipeline-1-java:$image_tag .'
                
                // Push the Docker image to the registry
                sh 'cd coit-backend1 && docker push sandeshmarakini/pipeline-1-java:$image_tag'

		        // Run the docker container
		        sh 'cd coit-backend1 && docker run --name maven-build -d sandeshmarakini/pipeline-1-java:$image_tag'
		
		        sh 'sleep 20'
		        sh 'docker ps'
		        sh 'docker images'
            }
        }

	stage('Cleaning') {
            steps {
                // Stopping docker container
                sh 'docker stop maven-build'
		
		        // Deleting docker container
		        sh 'docker rm maven-build'
	
		        // Deleting docker image
		        sh 'docker rmi sandeshmarakini/pipeline-1-java:$image_tag'
                }
        }
	
	post {
		stage{
        		always {
            		// Archive artifacts
            		archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true

            		// Test reports
            		junit '**/target/surefire-reports/*.xml'
       		 		}
             
   		 }
	}
}
